// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fursa-platform/Applications.tsx": () => import("../components/mockups/fursa-platform/Applications.tsx"),
  "./components/mockups/fursa-platform/EmployerDashboard.tsx": () => import("../components/mockups/fursa-platform/EmployerDashboard.tsx"),
  "./components/mockups/fursa-platform/JobListings.tsx": () => import("../components/mockups/fursa-platform/JobListings.tsx"),
  "./components/mockups/fursa-platform/Landing.tsx": () => import("../components/mockups/fursa-platform/Landing.tsx"),
  "./components/mockups/fursa-platform/Profile.tsx": () => import("../components/mockups/fursa-platform/Profile.tsx"),
  "./components/mockups/fursa-platform/SeekerDashboard.tsx": () => import("../components/mockups/fursa-platform/SeekerDashboard.tsx")
};
